services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: pi-syncthing
    volumes:
      - /home/khem:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: always
